In [2]:
import numpy as numpy
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy.stats as stats
import numpy as np

In [3]:
path = "../halos_disk.npy"
matches = np.load(path, allow_pickle=True)

# Convertir a DataFrame
df = pd.DataFrame(list(matches))

In [6]:
df

,subhalo_TNG50-1,halo_TNG50-1,pos_TNG50-1,Mvir_TNG50-1,Rvir_TNG50-1,halo_TNG50-3,pos_TNG50-3,Mvir_TNG50-3,Rvir_TNG50-3,dist,dMvir,dRvir,cost
0,117251,3,"[15550.406, 29353.352, 25992.469]",3470.526367,3470.526367,3,"[15544.709, 29365.37, 26009.568]",3491.555176,664.569702,21.662817,0.006059,-0.808510,0.808557
1,117254,3,"[15550.406, 29353.352, 25992.469]",3470.526367,3470.526367,3,"[15544.709, 29365.37, 26009.568]",3491.555176,664.569702,21.662817,0.006059,-0.808510,0.808557
2,117255,3,"[15550.406, 29353.352, 25992.469]",3470.526367,3470.526367,3,"[15544.709, 29365.37, 26009.568]",3491.555176,664.569702,21.662817,0.006059,-0.808510,0.808557
3,117256,3,"[15550.406, 29353.352, 25992.469]",3470.526367,3470.526367,3,"[15544.709, 29365.37, 26009.568]",3491.555176,664.569702,21.662817,0.006059,-0.808510,0.808557
4,117257,3,"[15550.406, 29353.352, 25992.469]",3470.526367,3470.526367,3,"[15544.709, 29365.37, 26009.568]",3491.555176,664.569702,21.662817,0.006059,-0.808510,0.808557
...,...,...,...,...,...,...,...,...,...,...,...,...,...
372,8,0,"[7307.2407, 24550.361, 21302.58]",15167.142578,15167.142578,0,"[7301.2026, 24564.564, 21312.2]",15079.097656,1082.225708,18.185574,-0.005805,-0.928647,0.928666
373,96763,2,"[27095.834, 7552.9536, 4049.4746]",5243.999512,5243.999512,2,"[27097.137, 7563.983, 4060.1667]",5181.124023,758.016785,15.416366,-0.011990,-0.855451,0.855540
374,96765,2,"[27095.834, 7552.9536, 4049.4746]",5243.999512,5243.999512,2,"[27097.137, 7563.983, 4060.1667]",5181.124023,758.016785,15.416366,-0.011990,-0.855451,0.855540
375,96773,2,"[27095.834, 7552.9536, 4049.4746]",5243.999512,5243.999512,2,"[27097.137, 7563.983, 4060.1667]",5181.124023,758.016785,15.416366,-0.011990,-0.855451,0.855540
376,96774,2,"[27095.834, 7552.9536, 4049.4746]",5243.999512,5243.999512,2,"[27097.137, 7563.983, 4060.1667]",5181.124023,758.016785,15.416366,-0.011990,-0.855451,0.855540

In [5]:
#search for the cases where the id in TNG50-1 is different from id in TNG50-3
mismatches = df[df['halo_TNG50-3'] != df['halo_TNG50-1']]
mismatches

,subhalo_TNG50-1,halo_TNG50-1,pos_TNG50-1,Mvir_TNG50-1,Rvir_TNG50-1,halo_TNG50-3,pos_TNG50-3,Mvir_TNG50-3,Rvir_TNG50-3,dist,dMvir,dRvir,cost
56,208812,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.74553,0.746513
57,208813,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.74553,0.746513
58,208814,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.74553,0.746513
59,208815,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.74553,0.746513
60,208817,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.74553,0.746513
...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,471249,105,"[11557.326, 23590.512, 21912.908]",195.640350,195.640350,93,"[11556.269, 23607.291, 21913.053]",234.575790,270.165710,16.813215,0.199015,0.38093,0.438293
354,471996,106,"[11246.371, 18125.9, 3207.1018]",174.405029,174.405029,64034,"[11400.171, 18075.357, 3302.7295]",0.000000,0.000000,188.025604,-1.000000,-1.00000,1.778284
355,471997,106,"[11246.371, 18125.9, 3207.1018]",174.405029,174.405029,64034,"[11400.171, 18075.357, 3302.7295]",0.000000,0.000000,188.025604,-1.000000,-1.00000,1.778284
356,471998,106,"[11246.371, 18125.9, 3207.1018]",174.405029,174.405029,64034,"[11400.171, 18075.357, 3302.7295]",0.000000,0.000000,188.025604,-1.000000,-1.00000,1.778284
357,472548,107,"[31665.262, 16189.37, 3306.4087]",182.164703,182.164703,106,"[31660.787, 16187.715, 3312.5867]",195.420303,254.207230,7.805734,0.072767,0.39548,0.404395

In [8]:
nHalos_fof = df['halo_TNG50-1'].nunique()
nHalos_fof

108