In [2]:
import numpy as numpy
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as stats
import numpy as np

In [26]:
path = "../halos_disk.npy"
matches = np.load(path, allow_pickle=True)

# Convertir a DataFrame
df = pd.DataFrame(list(matches))

# solo halos con masa mayor a 3.16 (esto es 10^10.5 en las unidades de TNG)
#df = df[df['Mvir_TNG50-1'] > 200]
len(df)

377

In [27]:
df['Mvir_TNG50-1'].min()

107.66678619384766

In [22]:
#search for the cases where the id in TNG50-1 is different from id in TNG50-3
mismatches = df[df['halo_TNG50-3'] != df['halo_TNG50-1']]
mismatches

,subhalo_TNG50-1,halo_TNG50-1,pos_TNG50-1,Mvir_TNG50-1,Rvir_TNG50-1,halo_TNG50-3,pos_TNG50-3,Mvir_TNG50-3,Rvir_TNG50-3,dist,dMvir,dRvir,cost
56,208812,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.745530,0.038307
57,208813,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.745530,0.038307
58,208814,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.745530,0.038307
59,208815,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.745530,0.038307
60,208817,8,"[3631.6023, 18741.941, 13207.412]",2301.364258,2301.364258,9,"[3626.7205, 18742.219, 13210.968]",2389.316162,585.628357,6.045824,0.038217,-0.745530,0.038307
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,457431,92,"[1393.5878, 19753.785, 6434.0723]",205.732498,205.732498,88,"[1387.3671, 19772.47, 6431.476]",227.007553,267.224335,19.864214,0.103411,0.298892,0.141480
326,457432,92,"[1393.5878, 19753.785, 6434.0723]",205.732498,205.732498,88,"[1387.3671, 19772.47, 6431.476]",227.007553,267.224335,19.864214,0.103411,0.298892,0.141480
338,461785,96,"[2841.1348, 6256.38, 24617.537]",218.381592,218.381592,83,"[2835.655, 6243.8706, 24633.252]",245.048065,274.118896,20.819843,0.122110,0.255229,0.154919
342,465255,99,"[20781.982, 26820.826, 23917.203]",200.465546,200.465546,66,"[20762.629, 26831.11, 23939.049]",242.333115,273.113220,30.944105,0.208852,0.362395,0.259704
343,465256,99,"[20781.982, 26820.826, 23917.203]",200.465546,200.465546,66,"[20762.629, 26831.11, 23939.049]",242.333115,273.113220,30.944105,0.208852,0.362395,0.259704

In [23]:
nHalos_fof = df['halo_TNG50-1'].nunique()
nHalos_fof

86

In [24]:
#halos que tienen masas iguales a 0 en TNG50-3
zero_mass = df[df['Mvir_TNG50-3'] < 1]
zero_mass

Empty DataFrame
Columns: [subhalo_TNG50-1, halo_TNG50-1, pos_TNG50-1, Mvir_TNG50-1, Rvir_TNG50-1, halo_TNG50-3, pos_TNG50-3, Mvir_TNG50-3, Rvir_TNG50-3, dist, dMvir, dRvir, cost]
Index: []

In [25]:
df['Mvir_TNG50-3'].min()

204.06704711914062